"""Increase password_hash length

Revision ID: 22c3619d0742
Revises: 
Create Date: 2024-10-13 09:29:50.590797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c3619d0742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('debtor_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('debtor_account', sa.String(length=34), nullable=False))
        batch_op.add_column(sa.Column('creditor_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('creditor_account', sa.String(length=34), nullable=False))
        batch_op.add_column(sa.Column('remittance_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mandate_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('original_message_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('original_message_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('group_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('requested_execution_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('requested_collection_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('case_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('creator', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.String(length=34), nullable=True))
        batch_op.add_column(sa.Column('statement_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('creation_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('bank_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ach_response', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('ach_response')
        batch_op.drop_column('bank_response')
        batch_op.drop_column('balance')
        batch_op.drop_column('creation_date_time')
        batch_op.drop_column('statement_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('creator')
        batch_op.drop_column('case_id')
        batch_op.drop_column('return_reason')
        batch_op.drop_column('requested_collection_date')
        batch_op.drop_column('requested_execution_date')
        batch_op.drop_column('group_status')
        batch_op.drop_column('original_message_type')
        batch_op.drop_column('original_message_id')
        batch_op.drop_column('mandate_id')
        batch_op.drop_column('remittance_info')
        batch_op.drop_column('creditor_account')
        batch_op.drop_column('creditor_name')
        batch_op.drop_column('debtor_account')
        batch_op.drop_column('debtor_name')
        batch_op.drop_column('currency')
        batch_op.drop_column('amount')
        batch_op.drop_column('reason')
        batch_op.drop_column('status')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
