"""Add custom_icon field to User model

Revision ID: 38977cc013df
Revises: 22c3619d0742
Create Date: 2024-10-13 09:41:21.659487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38977cc013df'
down_revision = '22c3619d0742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=34), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('cvv', sa.String(length=3), nullable=False),
    sa.Column('cardholder_name', sa.String(length=128), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_icon', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('custom_icon')

    op.drop_table('debit_card')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
