"""Add icon_position to User model

Revision ID: 98e27b580bc6
Revises: 38977cc013df
Create Date: 2024-10-14 03:53:17.046666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98e27b580bc6'
down_revision = '38977cc013df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('account_id')
        batch_op.drop_column('debtor_account')
        batch_op.drop_column('reason')
        batch_op.drop_column('group_status')
        batch_op.drop_column('statement_id')
        batch_op.drop_column('return_reason')
        batch_op.drop_column('requested_execution_date')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('creditor_account')
        batch_op.drop_column('balance')
        batch_op.drop_column('mandate_id')
        batch_op.drop_column('remittance_info')
        batch_op.drop_column('bank_response')
        batch_op.drop_column('transaction_hash')
        batch_op.drop_column('requested_collection_date')
        batch_op.drop_column('message_type')
        batch_op.drop_column('original_message_type')
        batch_op.drop_column('creator')
        batch_op.drop_column('ach_response')
        batch_op.drop_column('creation_date_time')
        batch_op.drop_column('original_message_id')
        batch_op.drop_column('iso20022_data')
        batch_op.drop_column('case_id')
        batch_op.drop_column('ethereum_data')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_position', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('is_business', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_business')
        batch_op.drop_column('icon_position')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ethereum_data', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('case_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('iso20022_data', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_message_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creation_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ach_response', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creator', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_message_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requested_collection_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank_response', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remittance_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mandate_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creditor_account', sa.VARCHAR(length=34), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requested_execution_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('statement_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('group_status', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('debtor_account', sa.VARCHAR(length=34), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.VARCHAR(length=34), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
